on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l app
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (cruptd36_left)
        run: west build -s app -b seeeduino_xiao_rp2040 -- -DSHIELD=cruptd36_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/app"
      - name: cruptd36 Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 cruptd36_left.uf2
      - name: West Build (cruptd36_right) 
        run: west build --pristine -s app -b seeeduino_xiao_rp2040 -- -DSHIELD=cruptd36_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/app"
      - name: cruptd36 Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 cruptd36_right.uf2
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            cruptd36_left.uf2
            cruptd36_right.uf2
